### ISSUE TITLE
users' data duplicated

### ISSUE THREAD

**Issue by Sunev** [uhyo/jinrou#71]
You may try this on your server.
``````
const crypto = require('crypto');

// mongoexport --db jinrou --collection users --jsonArray --out user.json
const users = require("./user.json")
var list = {}
for (let i in users) {
    let user = users[i];
    if (user.userid) {
        let hashid = crypto.createHash("md5")
        hashid.update(user.userid)
        user.userid = hashid.digest("hex")
        if (list[user.userid] == undefined) {
            list[user.userid] = 1
        } else {
            list[user.userid]++;
        }
    }
}

var result = JSON.parse(JSON.stringify(list, (key, value) => {
    if (value && value <= 1) {
        return undefined
    } else {
        return value
    }
}))

console.log(JSON.stringify(result, null, 4))
console.log(`${Object.keys(result).length} users duplicated`)
process.exit(0)
``````
I got ```50 users duplicated```

**Comment by uhyo** [comment]
Yes, it turned out that I have 92 duplicated users out of 31809 registered users.
In addition to dealing with possible duplicate event handlers,
it seems that we have to make some indices unique indices so that duplicate documents will never be inserted.
The problem is how we can sanitize duplicate documents already in our DB,
because a unique index cannot be created if there already are duplicate documents.

**Comment by Sunev** [comment]
I'd like to suggest a ```repair8.js``` for merging those already exist.
And actully an unique index is also necessary for all other collections, like ```game```, ```room```, ```userlogs```

**Comment by uhyo** [comment]
Good idea. I'm going to work on it.

**Comment by uhyo** [comment]
This commit adds `repair8.js`.
It should work, but is not yet tested on my production server.
I'm going to test it tomorrow.

Caveat: you have to manually remove & recreate indices to make them unique indices.
I tried to automate this but it did not work due to `driver is incompatible with this server version` error, at least on my local mongodb.

**Comment by Sunev** [comment]
Thanks a lot. I will try it later.

**Comment by uhyo** [comment]
I tried it on my server.
It apparently worked well.

**Comment by Sunev** [comment]
Pretty busy for last 2 weeks.
I tried ```repair8.js``` out just now, it worked very well.

I'm just not quite sure about
> manually remove & recreate indices

Do you mean to [db.collection.dropIndexes()](https://docs.mongodb.com/manual/reference/method/db.collection.dropIndexes/), and then ```./server/db.coffee``` would ensure unique index?

**Comment by uhyo** [comment]
Yes, removing indices and restarting the server should recreate unique indices.
