### ISSUE TITLE
When a AbsoluteWolf become Hooliganattacker , he will die by voted

### ISSUE THREAD

**Issue by YagamiMirai** [uhyo/jinrou#770]
Uhyoさん，Hello again~

There is a new question：

When a AbsoluteWolf become Hooliganattacker by Hooligan，（and there is another werewolf still alive，）He will lose the ability to be immune to death，and die by the voted.

But Hooliganattacker will not change the character's team，so It might be a bug？

link：
room：https://www.werewolf.com.cn/room/183181
chinese ver：https://github.com/Sunev/jinrou/issues/172

**Comment by uhyo** [comment]
Hello, thank you for your report :smiley:

But this seems an intentional behavior. Being a HooliganAttacker contributes to Hooligan team's win, so it is given a similar property to not being in Werewolves team.

To verify this, I took a look at the documentation site and found that it explicitly says AbsoluteWolf loses immortality after becoming a HooliganAttacker.

> ただし、以下のいずれかの条件を満たした場合は通常通り死亡します。
>
> - 暴動者になった場合。
>
> https://jinrou-doc.uhyohyo.net/jobs/absolutewolf

Hope this helps 🙂

**Comment by YagamiMirai** [comment]
Got it. Sorry I forgot to check the document first...
